### ISSUE TITLE
Compiled Windows guide with all issues fixed

### ISSUE THREAD

**Issue by nitinmukesh** [ASLP-lab/DiffRhythm#22]
https://youtu.be/J8FejpiGcAU

Credits to @lethanner for his help in solving issues

**Comment by lethanner** [comment]
Are you really got perfect English pronunciation using Japanese voice models?
I can't understand any English words in my generated audios.

**Comment by nitinmukesh** [comment]
except for few words. I haven't done enough testing though, will try this weekend.

**Comment by lethanner** [comment]
> Japanese voice models

Pardon. Japanese voice are not really used in the inference. It is only used during initialization.
See https://github.com/ASLP-lab/DiffRhythm/issues/17#issuecomment-2705058729 for explanation.

**Comment by nitinmukesh** [comment]
I read your detailed analysis, thank for sharing it.

**Comment by Sxrjs2010** [comment]
Thanks

**Comment by sujitvasanth** [comment]
thanks for this... I also created a summary of what I needed to make it work on windows for someone on the discord channel that was struggling - much. much easier to run on ubuntu..(!)

[To create a windows local server us.txt](https://github.com/user-attachments/files/19180193/To.create.a.windows.local.server.us.txt)

**Comment by NZqian** [comment]
Japanese is now temporarily removed, so I believe this issue is solved XD

**Comment by erhan-** [comment]
Doing just a fresh install on Windows with current master and it is not solved:

> RuntimeError: failed to load voice "ja"

Besides this is more supposed to be a guide and should be in a markdown file instead of an issue.

**Comment by nitinmukesh** [comment]
This was closed for a reason. With new updates released yesterday some issues are fixed and no longer require manually downloading of files.

**Comment by erhan-** [comment]
I created a pull request here to fix it: https://github.com/ASLP-lab/DiffRhythm/pull/44

**Comment by erhan-** [comment]
Sorry for the mixup. I though the response came from NZqian. The content is still valid though and the PR is required.

**Comment by zhaojigang** [comment]
> 4\. alteration

hi where is app.py file, i dont find this file in this repository

**Comment by nitinmukesh** [comment]
> > 4. alteration
> 
> hi where is app.py file, i dont find this file in this repository

Just follow the guide and you will find it. There is an installation guide in video description.
https://youtu.be/hKb8lNuxIRU
